# Generated by Django 4.0.3 on 2022-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desprendibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quincena', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('año', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPRESA', models.CharField(max_length=64)),
                ('EMPLEADO', models.CharField(max_length=64)),
                ('FECHARETIRO', models.CharField(max_length=64)),
                ('TOTALSUELDO', models.CharField(max_length=64)),
                ('OTROS', models.CharField(max_length=64)),
                ('CODCC', models.CharField(max_length=64)),
                ('NOMCC', models.CharField(max_length=64)),
                ('SEXO', models.CharField(max_length=64)),
                ('TIPODOCUMENTO', models.CharField(max_length=64)),
                ('NÚMERODEIDENTIFICACIÓN', models.CharField(max_length=64)),
                ('CIUDADDOCUMENTO', models.CharField(max_length=64)),
                ('FECHADENACIMIENTO', models.CharField(max_length=64)),
                ('CIUDADDENACIMIENTO', models.CharField(max_length=64)),
                ('FECHADEINGRESO', models.CharField(max_length=64)),
                ('CÓDIGOEMPLEDO', models.CharField(max_length=64)),
                ('NOMBREDELCARGO', models.CharField(max_length=64)),
                ('MOTIVODELCARGO', models.CharField(max_length=64)),
                ('NOMBREESTRUCTURACARGO', models.CharField(max_length=64)),
                ('DESCRIPCIÓNDELMOTIVO', models.CharField(max_length=64)),
                ('VALORSUELDO', models.CharField(max_length=64)),
                ('MOTIVOCONTRATO', models.CharField(max_length=64)),
                ('TIPODECONTRATO', models.CharField(max_length=64)),
                ('NOMBRETIPOTRABAJADOR', models.CharField(max_length=64)),
                ('NOMBRETIPOSALARIO', models.CharField(max_length=64)),
                ('NOMBRENORMALABORAL', models.CharField(max_length=64)),
                ('NOMBRELEGISLACIÓNLABORAL', models.CharField(max_length=64)),
                ('UBICACIÓNGEOGRÁFICA', models.CharField(max_length=64)),
                ('NOMBREJORNADA', models.CharField(max_length=64)),
                ('NOMBREFORMADEPAGO', models.CharField(max_length=64)),
                ('CUENTADEPAGO', models.CharField(max_length=64)),
                ('TIPOCUENTA', models.CharField(max_length=64)),
                ('SUCURSALDEPAGO', models.CharField(max_length=64)),
                ('METODODEPAGO', models.CharField(max_length=64)),
                ('EPS', models.CharField(max_length=64)),
                ('FONDOSDEPENSIONES', models.CharField(max_length=64)),
                ('FONDODECESANTÍAS', models.CharField(max_length=64)),
                ('RIESGOSPROFESIONALES', models.CharField(max_length=64)),
                ('CAJADECOMPENSACIÓN', models.CharField(max_length=64)),
                ('COUNTEMPLEADOPEREMPRESA', models.CharField(max_length=64)),
                ('COUNTEMPRESAPERREPORT', models.CharField(max_length=64)),
                ('COUNTEMPLEADOPERREPORT', models.CharField(max_length=64)),
            ],
        ),
    ]
